name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/ztig3r/nixoweb:latest
    
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/nixoweb:latest
