name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  call-build:
    uses: zTig3r/workflows/.github/workflows/build-and-push-docker-image.yml@master
    with:
      project_name: 'nixoweb'
